spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:7000/
          predicates:
            - Path=/categories/**
        - id: r2
          uri: http://localhost:7001/
          predicates:
            - Path=/produits/**
    discovery:
      enabled: false
server:
  port: 8888